# Generated by Django 4.2.3 on 2023-07-06 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegionOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название зоны исследования')),
                ('icon', models.FileField(upload_to='region_of_interest', verbose_name='Иконка зоны исследования')),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название специализации')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок описания')),
                ('text', models.TextField(verbose_name='Текст описания')),
                ('datetime_of_creation', models.DateTimeField(auto_now_add=True)),
                ('datetime_of_change', models.DateTimeField(auto_now=True)),
                ('modality', models.CharField(choices=[('RG', 'Rg'), ('CT', 'CT'), ('MRI', 'MRI')], default='', max_length=3)),
                ('region_of_interest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sample.regionofinterest')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sample.specialization')),
            ],
        ),
    ]
