# Generated by Django 4.2.3 on 2024-02-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_sample_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='additional_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Дополнительное изображение'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
